// Code generated by protoc-gen-go.
// source: dog.proto
// DO NOT EDIT!

package demo

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type Dog struct {
	Barks    bool          `protobuf:"varint,1,opt,name=barks" json:"barks,omitempty"`
	Yearsold int32         `protobuf:"varint,2,opt,name=yearsold" json:"yearsold,omitempty"`
	Parents  []*Dog_Parent `protobuf:"bytes,4,rep,name=parents" json:"parents,omitempty"`
}

func (m *Dog) Reset()         { *m = Dog{} }
func (m *Dog) String() string { return proto.CompactTextString(m) }
func (*Dog) ProtoMessage()    {}

func (m *Dog) GetParents() []*Dog_Parent {
	if m != nil {
		return m.Parents
	}
	return nil
}

type Dog_Parent struct {
	Name  string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Email string `protobuf:"bytes,2,opt,name=email" json:"email,omitempty"`
}

func (m *Dog_Parent) Reset()         { *m = Dog_Parent{} }
func (m *Dog_Parent) String() string { return proto.CompactTextString(m) }
func (*Dog_Parent) ProtoMessage()    {}
